### ISSUE TITLE
Kein Redmine-Account

### ISSUE THREAD

**Issue by felixthomas** [swenib/grp2A-pizza#1]
Hallo Herr Prof. Dr. Braun,

ich habe leider keinen Zugriff auf Redmine. Der Benutzer oder das Kennwort sind ungültig.
Ich habe versucht mich mit meiner ifw-Kennung anzumelden.
Könnten Sie das bitte prüfen?

Vielen Dank im Voraus
Felix Thomas

**Comment by obcode** [comment]
Funktioniert Ihr Account den sonst mit dem Passwort? Laut Redmine sind Sie an Board:

https://www.dropbox.com/s/jyzlx5pj3pl8n9v/Screenshot%202017-04-02%2014.39.46.png?dl=0

**Comment by felixthomas** [comment]
Danke für die Rückmeldung. Das Problem hat sich erledigt.
